In [2]:
import pandas as pd
DataFrame = 'C:/Users/jabra/mda610/lesson1/hw6/Miete.csv'
MF = pd.read_csv(DataFrame)
MF

,Rent,FloorSpace,YearBuilt,Bath,CentralHeating,HotWater,TiledBath,WindowType,KitchenType,LeaseDuration,AgeCategory,FloorSpaceCategory,NetRentPerSqm,Rooms,AddressType,ResidenceType
0,693.29,50,1971,0,1,0,0,0,0,2,4,1,13.865800,1,2,2
1,736.60,70,1971,0,1,0,0,0,0,26,4,2,10.522857,3,2,2
2,732.23,50,1971,0,1,0,0,0,0,1,4,1,14.644600,1,2,2
3,1295.14,55,1893,0,1,0,0,0,0,0,1,2,23.548000,3,2,2
4,394.97,46,1957,0,0,1,0,0,0,27,3,1,8.586304,3,2,2
5,1285.64,94,1971,0,1,0,1,0,0,2,4,3,13.677021,4,2,2
6,476.31,28,1967,0,1,0,0,1,1,9,4,1,17.011071,1,2,2
7,709.57,36,1971,0,1,0,0,0,1,3,4,1,19.710278,1,2,2
8,852.74,33,1971,0,1,0,0,0,0,1,4,1,25.840606,1,2,2
9,657.44,57,1985,0,1,0,1,0,1,9,6,2,11.534035,2,2,2
10,1237.84,75,1985,0,1,0,1,0,1,3,6,2,16.504533,3,2,2
11,1212.03,83,1985,0,1,0,1,0,1,1,6,3,14.602771,3,2,2
12,527.54,50,1957,0,1,0,1,0,0,4,3,1,10.550800,2,2,2
13,1183.62,71,1989,0,1,0,1,0,1,3,6,2,16.670704,3,2,2
14,852.30,93,1971,0,1,0,1,0,0,4,4,3,9.164516,4,2,2
15,812.80,93,1971,0,1,0,1,0,0,12,4,3,8.739785,4,2,2
16,593.07,79,1971,0,1,0,0,0,0,20,4,2,7.507215,3,2,2
17,1623.63,60,1985,0,1,0,1,0,1,1,6,2,27.060500,2,3,3
18,2680.00,145,1971,0,1,0,1,0,1,2,4,3,18.482759,4,3,3
19,837.84,76,1957,0,1,0,0,0,0,20,3,2,11.024211,3,1,1
20,875.10,104,1957,0,1,0,1,0,0,3,3,3,8.414423,5,2,1
21,765.39,93,1971,0,1,0,1,0,0,3,4,3,8.230000,4,2,1
22,422.82,50,1957,0,0,0,0,0,0,9,3,1,8.456400,2,2,2
23,414.20,50,1880,0,0,0,0,0,0,8,1,1,8.284000,1,2,2
24,480.34,40,1959,0,1,0,0,0,0,2,3,1,12.008500,1,2,2
25,1454.12,74,1957,0,1,0,0,0,0,2,3,2,19.650270,3,2,2
26,759.20,76,1957,0,1,0,1,0,0,0,3,2,9.989474,3,2,2
27,700.00,36,1965,0,1,0,0,0,0,4,3,1,19.444444,2,2,2
28,670.86,59,1957,0,0,0,0,1,0,5,3,2,11.370508,1,2,2
29,380.00,40,1911,1,0,0,0,0,0,32,1,1,9.500000,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,787.36,79,1957,0,1,0,1,1,0,11,3,2,9.966582,4,2,2
1053,776.88,82,1957,0,1,0,1,1,0,7,3,3,9.474146,4,2,2
1054,900.00,80,1957,0,1,0,1,1,0,17,3,2,11.250000,4,2,2
1055,897.73,70,1971,0,1,0,0,0,0,4,4,2,12.824714,2,2,2
1056,1033.16,76,1957,0,1,0,1,0,1,12,3,2,13.594211,4,2,2
1057,580.00,58,1971,0,1,0,1,0,0,1,4,2,10.000000,2,2,2
1058,930.00,96,1971,0,1,0,1,0,0,19,4,3,9.687500,4,2,2
1059,1467.26,65,1980,0,1,0,1,0,0,5,5,2,22.573231,3,2,3
1060,572.11,45,1956,0,1,0,1,0,0,1,3,1,12.713556,2,2,3
1061,659.65,45,1956,0,1,0,1,0,0,1,3,1,14.658889,2,2,3
1062,654.94,40,1957,0,1,0,1,0,0,2,3,1,16.373500,2,2,2
1063,667.78,90,1971,0,1,0,1,0,0,2,4,3,7.419778,4,2,2
1064,454.81,55,1957,1,0,0,0,0,0,23,3,2,8.269273,2,2,2
1065,1209.10,70,1957,0,1,0,1,0,0,1,3,2,17.272857,2,2,2
1066,524.81,58,1969,0,1,0,1,0,0,18,4,2,9.048448,2,2,2
1067,1281.17,76,1971,0,1,0,1,0,0,10,4,2,16.857500,3,3,3
1068,848.65,65,1971,0,1,0,0,0,0,25,4,2,13.056154,2,2,2
1069,2130.22,109,1957,0,1,0,1,0,0,1,3,3,19.543303,5,3,3
1070,708.15,65,1893,0,0,1,0,0,0,2,1,2,10.894615,3,2,1
1071,1502.24,95,1989,0,1,0,1,0,0,4,6,3,15.813053,3,2,2
1072,697.10,65,1989,0,1,0,1,0,0,4,6,2,10.724615,2,2,2
1073,1160.34,96,1971,0,1,0,1,0,0,6,4,3,12.086875,3,2,3
1074,2021.16,95,1969,0,1,0,0,0,0,1,4,3,21.275368,3,2,3
1075,452.52,92,1957,0,1,0,0,0,0,6,3,3,4.918696,3,2,3
1076,1281.40,60,1973,0,1,0,1,0,0,0,4,2,21.356667,3,2,3
1077,644.86,52,1974,0,1,0,1,0,0,0,4,2,12.401154,2,2,3
1078,779.58,23,1974,0,1,0,1,0,1,4,4,1,33.894783,1,2,3
1079,662.76,30,1964,0,1,0,0,0,0,1,3,1,22.092000,1,2,3
1080,709.96,50,1969,0,1,0,1,0,0,1,4,1,14.199200,1,2,3
1081,476.56,60,1939,0,1,0,0,0,0,1,2,2,7.942667,2,2,3